#命令别名 {{{
alias vialias='vi ~/.bash_aliases'
alias usb='pmount /dev/sdb1'
alias winc='sudo mount -t ntfs-3g /dev/sda2 /home/tao/c'
alias wind='sudo mount -t ntfs-3g /dev/sda1 /home/tao/d'
alias sy='sudo synaptic-pkexec'
alias remove='sudo apt remove'
alias sdb='sudo updatedb'
alias h='htop'
alias svi='sudo vim'
alias findps='ps -ef | grep '
alias con='vim ~/.i3/config'
alias top10='print -l  ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
alias show='apt-cache show'
alias downiso='wget http://mirrors.ustc.edu.cn/debian-cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso'
alias t='tldr'
alias fhttp='python3 -m http.server'
alias l='locate'
alias a='sudo apt-get install'
alias inst='sudo aptitude install'
alias s='aptitude search'
alias fixit='sudo apt --fix-broken install'

alias cp='cp -i'
alias con='vim ~/.i3/config'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls -F --color=auto'
alias ll='ls -lh'
alias grep='grep --color=auto'
alias la='ls -a'

# alias cd1='sudo mount -t iso9660 /home/debian-9.7.0-amd64-DVD-1.iso /media/cdrom'
# alias qemuiso='qemu-system-x86_64 -enable-kvm -m 1GB -vga qxl -cdrom'
# alias qemuimg='qemu-system-x86_64 -enable-kvm -m 1GB -vga qxl -hda'

#}}}
